# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 19:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_attachment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attachment',
            old_name='attachment',
            new_name='author',
        ),
    ]
