# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-02 14:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20171025_2131'),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posteater',
            name='attachment_eater',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.Attachment'),
        ),
    ]
