# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-02 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20180102_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='posteater',
            name='eat',
            field=models.BooleanField(default=True),
        ),
    ]
