# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-02 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20180102_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posteater',
            name='submit_time',
            field=models.DateTimeField(auto_now_add=True, unique_for_month=True),
        ),
    ]
