# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-02 15:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20180102_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='posteater',
            name='title',
            field=models.CharField(default='hoi', max_length=30, unique_for_month='submit_time'),
        ),
        migrations.AlterField(
            model_name='posteater',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
