# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-03 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_remove_postcook_eat_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcook',
            name='food',
        ),
        migrations.AlterField(
            model_name='postcook',
            name='extra_eater_allergy',
            field=models.CharField(blank=True, default=0, max_length=124),
        ),
        migrations.AlterField(
            model_name='postcook',
            name='extra_eater_veg',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='postcook',
            name='extra_eaters',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
    ]
