# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-03 13:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_auto_20180103_1218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcook',
            name='id',
        ),
        migrations.AddField(
            model_name='postcook',
            name='eater',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='posts.PostEater'),
        ),
    ]
