# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-12 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0019_auto_20180103_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posteater',
            name='submit_time',
            field=models.DateTimeField(),
        ),
    ]
