# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-13 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0020_auto_20180112_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcook',
            name='submit_time',
            field=models.DateTimeField(),
        ),
    ]
