# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-27 13:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0022_posteater_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posteater',
            name='event',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='schedule.Event'),
        ),
    ]
