# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-27 13:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0023_auto_20180127_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posteater',
            name='event',
        ),
    ]
