# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-28 20:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0024_remove_posteater_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='posteater',
            name='description',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='posteater',
            name='startDateTime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
