# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-27 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0025_auto_20180127_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posteater',
            name='startDateTime',
            field=models.DateTimeField(),
        ),
    ]
