# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-27 14:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0026_auto_20180127_1514'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posteater',
            old_name='title',
            new_name='description',
        ),
    ]
