# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-08 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0026_auto_20180128_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcook',
            name='description',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='postcook',
            name='eat_time',
            field=models.TimeField(default='18:30'),
        ),
        migrations.AddField(
            model_name='postcook',
            name='food',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='postcook',
            name='startDateTime',
            field=models.DateTimeField(auto_now_add=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='postcook',
            name='submit_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='posteater',
            name='startDateTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='posteater',
            name='submit_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
