# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-28 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0026_auto_20180128_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posteater',
            name='startDateTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='posteater',
            name='submit_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
