# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-27 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0027_auto_20180127_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcook',
            name='description',
            field=models.CharField(default='bitches', max_length=30),
        ),
        migrations.AddField(
            model_name='postcook',
            name='startDateTime',
            field=models.DateTimeField(default=1),
            preserve_default=False,
        ),
    ]
