# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-05 08:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0027_auto_20180128_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcook',
            name='description',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='postcook',
            name='startDateTime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='postcook',
            name='submit_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
