# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-27 15:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0028_auto_20180127_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcook',
            name='description',
        ),
        migrations.RemoveField(
            model_name='postcook',
            name='startDateTime',
        ),
    ]
