# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-06 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0028_auto_20180405_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcook',
            name='eat_time',
            field=models.TimeField(default='18:30'),
        ),
        migrations.AddField(
            model_name='postcook',
            name='food',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
