# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-27 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0029_auto_20180127_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posteater',
            name='startDateTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
